- name: Download grafana installer
  ansible.builtin.apt:
    deb: https://dl.grafana.com/oss/release/grafana_10.3.1_amd64.deb
  become: true

- name: Start grafana service
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
