---
- name: Fail distribution
  ansible.builtin.fail:
    msg: "Distribution {{ ansible_distribution }} is not configured"
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: Check debian-based system
  ansible.builtin.include_tasks: debian-based.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
