- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - adduser
      - libfontconfig1
      - musl
      - curl
      - wget
    state: present
    update_cache: true
  become: true
