test:
  hosts:
    altair:
      ansible_host: "netangels.altair"
      ansible_user: "root"

rebrain:
  hosts:
    master:
      ansible_host: ""
      ansible_user: "user"
    backup:
      ansible_host: ""
      ansible_user: "user"

rebrain-master:
  hosts:
    master:
      ansible_host: ""
      ansible_user: "user"
