---
- name: Copy configuration
  ansible.builtin.template:
    src: configuration.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "644"
    backup: true
  become: true

- name: Restart keepalived service
  ansible.builtin.systemd_service:
    name: keepalived
    state: restarted
  become: true
